version: 2
updates:
  - package-ecosystem: "cargo"
    labels: ["dependabot"]
    directory: "/"
    schedule:
      interval: "daily"
 - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["dependabot"]
    schedule:
      interval: "daily"
