[package]
name = "withdrawals-meterer"
version = "0.1.11"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
ethers = "2.0.10"
metrics = "0.21.1"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.32.0", features = ["time", "rt"] }

client = { path = "../client" }
storage = { path = "../storage" }
vlog = { path = "../vlog" }
